"""rbac-tables-added

Revision ID: 21490779c2f5
Revises: 6735d368b960
Create Date: 2026-08-24 16:17:14.782217

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "21490779c2f5"
down_revision: str | Sequence[str] | None = "6735d368b960"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
